package com.cigolsoftware.cigol.measurement.enums;

public enum Magnitude {
	AMOUNT, AMOUNT_SUBSTANCE, AREA, CAPACITANCE, CATALYTIC_ACTIVITY, DOSE, ELECTRIC_CHARGE, ELECTRIC_CURRENT,
	ELECTRICAL_CONDUCTANCE, ENERGY, FORCE, FREQUENCY, ILLUMINANCE, IMPEDANCE, INDUCTANCE, LENGTH, LUMINOUS_FLUX,
	LUMINOUS_INTENSITY, MAGNETIC_FLUX, MAGNETIC_FLUX_DENSITY, MASS, PLANE_ANGLE, POWER, SOLID_ANGLE, STRESS,
	THERMODYNAMIC_TEMPERATURE, TIME, VERGENCE, VOLTAGE, VOLUME;
}
